// <auto-generated />
using System;
using HappyBirthdayEmployees.EmployeesDbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HappyBirthdayEmployees.EmployeesDbConnection.Migrations
{
    [DbContext(typeof(HappyBirthdayDbContext))]
    [Migration("20240328203711_AddIdMessangersEmployee")]
    partial class AddIdMessangersEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HappyBirthdayEmployees.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateBorn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_born");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<long?>("IdDiscord")
                        .HasColumnType("bigint")
                        .HasColumnName("id_discord");

                    b.Property<long?>("IdTelegram")
                        .HasColumnType("bigint")
                        .HasColumnName("id_telegram");

                    b.Property<string>("JobPosition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_position");

                    b.HasKey("Id");

                    b.ToTable("employee");
                });
#pragma warning restore 612, 618
        }
    }
}
